**LEARNING NumPy RANDOM FUNCTIONS**

Random numbers are those which cannot be predicted or put in a sequence. Computers use algorithms to generate randome numbers; these are called *pseudo-random* numbers.

In [6]:
from numpy import random # module in NumPy to generate random numbers

Random number may be generated using the `random` module in *NumPy*. The methods to create random numbers are:
+ `random.rand()` for float
+ `random.randint()` for int

These may be applied to generate an array of random numbers as well, by passing the array size as parameters. Besides these methods, we can use the `random.choice()` to select a random element of a given array.

In [7]:
print(random.randint(1, 100)) # generate a random integer between 1 and 100
print(random.rand()) # generate a random float between 0 and 1
print(random.randint(50, size=(3, 4)))
print(random.rand(4))
print(random.choice([2, 3, 4, 5, 7, 8, 1]))

69
0.8474290944437843
[[18 20 45 31]
 [46  0  6 10]
 [ 1 39 33 32]]
[0.98624562 0.52608127 0.7593254  0.43436647]
7
