**LEARNING NumPy RANDOM FUNCTIONS**

Random numbers are those which cannot be predicted or put in a sequence. Computers use algorithms to generate randome numbers; these are called *pseudo-random* numbers.

In [2]:
from numpy import random # module in NumPy to generate random numbers

Random number may be generated using the `random` module in *NumPy*. The methods to create random numbers are:
+ `random.rand()` for float
+ `random.randint()` for int

These may be applied to generate an array of random numbers as well, by passing the array size as parameters. Besides these methods, we can use the `random.choice()` to select a random element of a given array.

In [3]:
print(random.randint(1, 100)) # generate a random integer between 1 and 100
print(random.rand()) # generate a random float between 0 and 1
print(random.randint(50, size=(3, 4)))
print(random.rand(4))
print(random.choice([2, 3, 4, 5, 7, 8, 1]))

35
0.03287615248539055
[[13 21  4  7]
 [ 1 35 36 30]
 [13  8 11  6]]
[0.11163463 0.13824945 0.90797164 0.99815846]
2


DATA DISTRIBUTION

A *data distribution* is a list of all possible values, as well as how often each value occurs.

A *random distribution* is a set of random numbers that follow a *probability density function*. A probability density function is a function that describes a continuous probability.

We can generate random numbers on defined probabilities by using the `random.choice()` method. Here there are 3 main parameters:
+ The array of number to choose randomly from.
+ `p` ie. the probability that each number will be included.
+ `size` ie. the number of values to generate.

In [4]:
# generate 100 values from the given numbers [3, 5, 7, 9]
# the probability of each value occurring in the final distribution is given by the 'p' array. eg. 3 and 10% chance of occurring.
x=random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

[7 7 7 7 5 7 5 7 5 7 3 3 3 3 5 3 7 7 5 3 7 7 7 3 3 7 7 7 7 5 5 5 5 7 7 7 7
 7 7 7 7 7 7 5 7 7 3 3 7 3 5 5 7 7 7 7 7 7 3 7 5 7 7 5 5 7 7 7 7 7 7 7 7 7
 3 3 3 5 7 7 5 7 7 5 7 7 7 7 5 7 3 5 7 7 7 7 5 5 7 5]


notice that the number 9 did not appear at all in the distribution. This is because the probability of it, as given in the `p` array is 0.

Also note that the sum of probabilities must equal 1. ie. `0.1+0.3+0.6+0.0=1.0`

In [5]:
z = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(z)

[[7 5 7 7 7]
 [7 7 5 7 7]
 [5 7 7 7 7]]
